language: python

python:
  - "3.6"

node_js:
  - "node"

install:
  - pip install -r requirements.txt
  - npm install

script:
  - pytest
  - npm test

cache:
  - pip
  directories:
    - node_modules