'use strict';
const problem29 = require('./problem-0029');

let input = 100;

module.exports = {
  description: `How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ ${input} and 2 ≤ b ≤ ${input}?`,
  result: () => problem29.distinctPowers(input)
};
